name: 'publish package to npm'

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  info:
    runs-on: ubuntu-latest
    steps:
      - name: show job variables
        run: |
          echo "job variables: "
          echo ""
          echo " - repository           : ${{ github.repository }}."
          echo " - triggered event      : ${{ github.event_name }}"
          echo " - trigger branch       : ${{ github.ref_name }}"
          echo " - destination branch   : ${{ github.ref }}"

  main:
    runs-on: ubuntu-latest
    needs: [info]
    steps:
      - name: 1 - setup checkout
        uses: actions/checkout@v2
      - name: 2 - setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: 3 - setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: 4 - install dependencies
        run: |
          pnpm install
          pnpm run build
      - name: 5 - publish package to npm
        if: github.ref == 'refs/heads/master'
        run: |
          HUSKY=0 npm run pub