name: '2 - publish npm package'

on:
  push:
    branches: [ master ]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  info:
    runs-on: ubuntu-latest
    steps:
      - name: show job variables
        run: |
          echo "job variables: "
          echo ""
          echo " - repository            : ${{ github.repository }}."
          echo " - triggered event       : ${{ github.event_name }}"
          echo " - trigger branch        : ${{ github.ref_name }}"
          echo " - destination branch    : ${{ github.ref }}"
          echo " - is pull request merged: ${{ github.event.pull_request.merged }}"

  nodejs-ci:
    needs: [info]
    uses: lucasvtiradentes/gcal-sync/.github/workflows/reusable-nodejs-ci.yml@master

  publish:
    needs: [nodejs-ci]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: setup-checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install dependencies
        run:  npm install

      - name: build package
        run: npm run build

      - name: publish package
        run: HUSKY=0 npm run pub
